// Growmax GSC indexing fix - permanent redirects for Soft 404 / dead URLs
// Source of truth: growmax-seo/fixes/gsc-indexing-redirects.js (generated 2026-09-21)
// Consumed by next.config.ts redirects()

export const gscIndexingRedirects = [
  { source: '/about', destination: '/company/about', permanent: true },
  { source: '/ai-analytics', destination: '/minori-ai', permanent: true },
  { source: '/arc', destination: '/revenue-platform', permanent: true },
  { source: '/arc/ai/connect', destination: '/minori-ai/connect', permanent: true },
  { source: '/arc/compare/cin7', destination: '/revenue-platform/compare', permanent: true },
  { source: '/arc/compare/nowcommerce', destination: '/revenue-platform/compare', permanent: true },
  { source: '/arc/compare/pepperi', destination: '/revenue-platform/compare', permanent: true },
  { source: '/arc/compare/unleashed', destination: '/revenue-platform/compare', permanent: true },
  { source: '/arc/pricing', destination: '/demo', permanent: true },
  { source: '/author/aravindan', destination: '/company/about', permanent: true },
  { source: '/author/gnanavel', destination: '/company/about', permanent: true },
  { source: '/author/james-jonathan', destination: '/company/about', permanent: true },
  { source: '/author/sudhakar', destination: '/company/about', permanent: true },
  { source: '/author/surya-sk', destination: '/company/about', permanent: true },
  { source: '/b2b-commerce-cloud', destination: '/revenue-platform', permanent: true },
  { source: '/b2b-ecommerce-platform', destination: '/revenue-platform', permanent: true },
  { source: '/b2b-marketplace', destination: '/revenue-platform', permanent: true },
  { source: '/b2b2b-commerce-cloud', destination: '/revenue-platform', permanent: true },
  { source: '/b2b2c-commerce-cloud', destination: '/revenue-platform', permanent: true },
  { source: '/blog/b2b-ecommerce-industrial-distributors', destination: '/blog/ai-reshaping-b2b-ecommerce-industrial-distributors', permanent: true },
  { source: '/blog/b2b-ecommerce-platform-for-manufacturers', destination: '/blog/b2b-ecommerce-strategy-industrial-manufacturers', permanent: true },
  { source: '/blog/best-b2b-order-taking-apps-distributors', destination: '/blog/best-b2b-ordering-apps-distributors', permanent: true },
  { source: '/blog/digital-enabled-fmcg-wholesale-self-ordering-apps', destination: '/blog/digital-enabled-fmcg-wholesale-benefits-of-launching-self-ordering-apps-for-b2b-and-horeca-customers', permanent: true },
  { source: '/blog/fmcg-wholesale-b2b-self-ordering-app', destination: '/blog/digital-enabled-fmcg-wholesale-benefits-of-launching-self-ordering-apps-for-b2b-and-horeca-customers', permanent: true },
  { source: '/blog/sales-order-booking-app-zoho-inventory', destination: '/blog/a-comprehensive-sales-order-booking-app-for-zoho-inventory', permanent: true },
  { source: '/blog/spare-parts-management-software', destination: '/blog/best-spare-parts-management-software', permanent: true },
  { source: '/category/ai-insights', destination: '/blog', permanent: true },
  { source: '/category/b2b-ecommerce', destination: '/blog', permanent: true },
  { source: '/category/marketing', destination: '/blog', permanent: true },
  { source: '/category/sales', destination: '/blog', permanent: true },
  { source: '/commerce-cloud', destination: '/revenue-platform', permanent: true },
  { source: '/comparisons/orocommerce-b2b-alternatives', destination: '/comparisons/orocommerce-alternatives', permanent: true },
  { source: '/contact', destination: '/demo', permanent: true },
  { source: '/contact-us', destination: '/demo', permanent: true },
  { source: '/customer-support', destination: '/demo', permanent: true },
  { source: '/enterprise-ecommerce-platform', destination: '/revenue-platform', permanent: true },
  { source: '/headless-commerce', destination: '/revenue-platform', permanent: true },
  { source: '/integrations', destination: '/revenue-platform', permanent: true },
  { source: '/internal-collaboration', destination: '/revenue-platform', permanent: true },
  { source: '/msa', destination: '/terms-of-service', permanent: true },
  { source: '/new-home', destination: '/', permanent: true },
  { source: '/order-management', destination: '/revenue-platform', permanent: true },
  { source: '/product-catalog-management', destination: '/revenue-platform', permanent: true },
  { source: '/quote-management', destination: '/revenue-platform', permanent: true },
  { source: '/sales-rep-app', destination: '/revenue-platform', permanent: true },
  { source: '/sap-integration-with-growmax-cloud', destination: '/revenue-platform/compare', permanent: true },
  { source: '/spare-parts-ecommerce', destination: '/solutions/spare-parts-ecommerce', permanent: true },
  { source: '/storefront-management', destination: '/revenue-platform', permanent: true },
  { source: '/wholesale-ecommerce', destination: '/revenue-platform', permanent: true },
  { source: '/why-us', destination: '/company/about', permanent: true },
]
