import { ArrowRight, Check, FileText, PackageCheck, ShieldCheck, ShoppingCart } from 'lucide-react'
import TrackedLink from '@/components/analytics/TrackedLink'
import MinoriWorkbench from '@/components/minori/MinoriWorkbench'

const cta = '/demo?source=minori-ai-v2&module=minori-beta'
const outcomes = [
  { icon: FileText, title: 'Create accurate quotes', text: 'Use the right customer price, quantity, and terms — then review before sending.' },
  { icon: ShoppingCart, title: 'Prepare and place orders', text: 'Repeat a purchase or start a new one. Check the exact result before it is written.' },
  { icon: PackageCheck, title: 'Build product data', text: 'Turn spreadsheets, PDFs, images, and catalogues into records your team can use.' },
]
const examples = [
  ['Create quotes', '“Quote 24 cases of 18mm conduit for Northline Electrical using their account pricing.”', 'A prepared quote with price, quantity, terms, and any missing detail called out.'],
  ['Prepare orders', '“Repeat the seal kits we bought in March and send them to our Durban branch.”', 'A proposed order checked against the prior purchase, availability, and destination.'],
  ['Build product data', '“Use this supplier spreadsheet, PDF, and product images for the new valve range.”', 'Product records with source details organised, uncertain fields marked, and no silent guesses.'],
]

export default function MinoriV2() {
  return <main className="min-h-[100dvh] bg-growmax-white text-growmax-black">
    <section className="border-b-4 border-growmax-black bg-grid-blueprint pt-20 pb-7 md:pt-24 md:pb-8"><div className="container mx-auto px-4 md:px-8">
      <div className="flex flex-wrap items-center justify-between gap-3"><p className="border-l-2 border-growmax-red pl-3 font-mono text-[11px] font-bold uppercase tracking-[0.18em] text-growmax-red">Minori AI / private beta</p><span className="border-2 border-growmax-black bg-white px-3 py-1.5 font-mono text-[10px] font-bold uppercase tracking-widest">Human approval required</span></div>
      <div className="mt-6 grid gap-6 lg:grid-cols-[1.3fr_.7fr] lg:items-end"><div><h1 className="max-w-3xl text-4xl font-bold uppercase leading-[.94] tracking-[-.06em] sm:text-5xl md:text-6xl lg:text-7xl">Turn customer requests into <span className="text-growmax-red">quotes, orders,</span> and product data.</h1><p className="mt-4 max-w-2xl text-base leading-relaxed text-gray-600 md:text-lg">For manufacturers and distributors, Minori AI does the preparation. Your team reviews and approves what happens next.</p></div><div className="flex flex-col items-start gap-4 lg:pb-1"><TrackedLink href={cta} eventName="minori_cta_clicked" eventData={{ variant: 'v2', location: 'hero' }} className="inline-flex h-12 items-center gap-3 bg-growmax-red px-6 font-mono text-[11px] font-bold uppercase tracking-widest text-white shadow-[5px_5px_0px_0px_rgba(13,13,13,1)] hover:translate-x-1 hover:translate-y-1 hover:bg-growmax-black">See Minori AI in action <ArrowRight className="h-4 w-4" /></TrackedLink><TrackedLink href="#how-it-works" eventName="minori_detail_viewed" eventData={{ variant: 'v2', section: 'how_it_works' }} className="font-mono text-[11px] font-bold uppercase tracking-widest underline underline-offset-4">See how it works <ArrowRight className="ml-1 inline h-3 w-3" /></TrackedLink></div></div>
      <div className="mt-6 grid gap-2 md:grid-cols-3">{outcomes.map(({ icon: Icon, title, text }, i) => <article id={['create-quotes', 'orders', 'product-data'][i]} key={title} className={`border-2 border-growmax-black p-3.5 ${i === 1 ? 'bg-growmax-black text-white' : 'bg-white'}`}><div className="flex items-center gap-3"><Icon className="h-5 w-5 shrink-0 text-growmax-red" /><h2 className="text-sm font-bold uppercase leading-tight">{title}</h2></div><p className={`mt-1.5 text-xs leading-snug ${i === 1 ? 'text-gray-300' : 'text-gray-600'}`}>{text}</p></article>)}</div>
    </div></section>
    <section id="how-it-works" className="border-b border-gray-300 py-16 md:py-24"><div className="container mx-auto px-4 md:px-8"><p className="mb-4 font-mono text-xs font-bold uppercase tracking-widest text-growmax-red">01 / request to review</p><MinoriWorkbench /></div></section>
    <section className="bg-[#e8e8e5] py-20 md:py-28"><div className="container mx-auto px-4 md:px-8"><p className="font-mono text-xs font-bold uppercase tracking-widest text-growmax-red">02 / three jobs ready to move</p><div className="mt-10 space-y-5">{examples.map(([title, prompt, result], i) => <article key={title} className="grid gap-6 border-2 border-growmax-black bg-white p-6 md:grid-cols-[.55fr_1fr_1fr] md:p-8"><div><span className="font-mono text-xs text-growmax-red">0{i + 1}</span><h2 className="mt-5 text-2xl font-bold uppercase">{title}</h2></div><blockquote className="border-l-4 border-growmax-red bg-[#f1f1ef] p-4 text-base leading-relaxed">{prompt}</blockquote><p className="leading-relaxed text-gray-600"><strong className="text-growmax-black">Ready for review: </strong>{result}</p></article>)}</div></div></section>
    <section className="border-b border-gray-300 py-20 md:py-28"><div className="container mx-auto grid gap-12 px-4 md:grid-cols-[.7fr_1.3fr] md:px-8"><div><p className="font-mono text-xs font-bold uppercase tracking-widest text-growmax-red">03 / control stays visible</p><h2 className="mt-4 text-3xl font-bold uppercase md:text-5xl">Useful work. Clear boundaries.</h2></div><div className="grid gap-3 sm:grid-cols-2"><div className="border-2 border-growmax-black p-5"><ShieldCheck className="h-6 w-6 text-growmax-red" /><h3 className="mt-5 font-bold uppercase">Your pricing and terms</h3><p className="mt-2 text-sm leading-relaxed text-gray-600">Use the commercial information your team has access to.</p></div><div className="border-2 border-growmax-black p-5"><Check className="h-6 w-6 text-growmax-red" /><h3 className="mt-5 font-bold uppercase">Review before writes</h3><p className="mt-2 text-sm leading-relaxed text-gray-600">A person approves the exact change before it is applied.</p></div><div className="border-2 border-growmax-black p-5"><span className="font-mono text-2xl text-growmax-red">NO</span><h3 className="mt-3 font-bold uppercase">Refuse missing information</h3><p className="mt-2 text-sm leading-relaxed text-gray-600">If a detail is missing or access is not allowed, it says so.</p></div><div className="border-2 border-growmax-black p-5"><span className="font-mono text-2xl text-growmax-red">↶</span><h3 className="mt-3 font-bold uppercase">Undo where supported</h3><p className="mt-2 text-sm leading-relaxed text-gray-600">Reversal remains an explicit option when the work supports it.</p></div></div></div></section>
    <section className="bg-growmax-black py-20 text-white md:py-28"><div className="container mx-auto px-4 text-center md:px-8"><p className="font-mono text-xs font-bold uppercase tracking-widest text-growmax-red">Start with one real request</p><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-bold uppercase leading-tight md:text-6xl">Bring the work your team handles every day.</h2><TrackedLink href={cta} eventName="minori_cta_clicked" eventData={{ variant: 'v2', location: 'final' }} className="mt-9 inline-flex h-14 items-center gap-3 bg-growmax-red px-8 font-mono text-xs font-bold uppercase tracking-widest text-white hover:bg-white hover:text-growmax-black">Book a Minori AI demo <ArrowRight className="h-4 w-4" /></TrackedLink></div></section>
  </main>
}