import type { Metadata } from 'next'
import { ArrowRight, Check, FileText, Package, ShoppingCart } from 'lucide-react'
import ReplayPlayer from '@/components/arc/ReplayPlayer'
import TrackedLink from '@/components/analytics/TrackedLink'

export const minoriV1Metadata: Metadata = {
  title: 'Minori AI for manufacturers and distributors | Growmax',
  description: 'Minori AI turns everyday requests into accurate quotes, approved orders, and structured product data for manufacturers and distributors.',
  alternates: { canonical: 'https://www.growmax.io/minori-ai/original' },
  robots: { index: false, follow: true },
}

const outcomes = [
  { icon: FileText, label: 'Quotes that hold up', title: 'Create a quote using the price and terms your customer actually gets.', text: 'Minori AI works from your account rules, price lists, quantities, and commercial terms. It does not guess at the number.' },
  { icon: ShoppingCart, label: 'Orders with a clear yes', title: 'Place a new order or repeat one without losing the human check.', text: 'A person reviews what will happen before anything is written. Approval is part of the work, not an afterthought.' },
  { icon: Package, label: 'Products from the pile', title: 'Turn spreadsheets, PDFs, images, and catalogues into usable products.', text: 'Start with the files your team already has. Minori AI finds the useful details, prepares the record, and leaves review to your team.' },
]

export default function MinoriV1() {
  const cta = '/demo?source=minori-ai-v1&module=minori-beta'
  return <main className="min-h-[100dvh] bg-growmax-white text-growmax-black">
    <section className="relative overflow-hidden border-b-4 border-growmax-black bg-grid-blueprint pt-24 pb-20 md:pt-36 md:pb-28"><div className="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-growmax-white/95" /><div className="container relative z-10 mx-auto px-4 md:px-8">
      <p className="mb-7 border-l-2 border-growmax-red pl-3 font-mono text-xs font-bold uppercase tracking-[0.18em] text-growmax-red">Minori AI · for the work behind every sale</p><h1 className="max-w-5xl text-5xl font-bold uppercase leading-[.91] tracking-[-.07em] sm:text-7xl md:text-9xl">Your request in.<br /><span className="text-growmax-red">Useful work out.</span></h1>
      <div className="mt-10 grid max-w-4xl gap-8 border-t-2 border-growmax-black pt-7 md:grid-cols-[1fr_auto] md:items-end"><p className="text-lg leading-relaxed text-gray-600 md:text-2xl">Minori AI helps manufacturers and distributors create accurate quotes, place approved orders, and make product information usable.</p><TrackedLink href={cta} eventName="minori_cta_clicked" eventData={{ variant: 'v1', location: 'hero' }} className="inline-flex h-14 items-center justify-center gap-3 whitespace-nowrap bg-growmax-red px-7 font-mono text-xs font-bold uppercase tracking-widest text-white shadow-[6px_6px_0px_0px_rgba(13,13,13,1)]">See Minori AI <ArrowRight className="h-4 w-4" /></TrackedLink></div>
    </div></section>
    <section className="border-b border-gray-300 py-20 md:py-28"><div className="container mx-auto px-4 md:px-8"><div className="mb-12 max-w-2xl"><p className="mb-4 font-mono text-xs font-bold uppercase tracking-widest text-growmax-red">Three jobs. One practical layer.</p><h2 className="text-3xl font-bold uppercase leading-tight tracking-tight md:text-5xl">Less chasing. More work that is ready to move.</h2></div><div className="grid gap-5 lg:grid-cols-3">{outcomes.map(({ icon: Icon, label, title, text }) => <article key={label} className="border-2 border-growmax-black bg-white p-6 shadow-[6px_6px_0px_0px_rgba(230,26,26,1)]"><Icon className="h-7 w-7 text-growmax-red" /><p className="mt-10 font-mono text-[10px] font-bold uppercase tracking-widest text-growmax-red">{label}</p><h3 className="mt-3 text-2xl font-bold uppercase leading-tight">{title}</h3><p className="mt-5 leading-relaxed text-gray-600">{text}</p></article>)}</div></div></section>
    <section id="replay" className="bg-[#e8e8e5] py-20 md:py-28"><div className="container mx-auto px-4 md:px-8"><p className="mb-3 font-mono text-xs font-bold uppercase tracking-widest text-growmax-red">See the work unfold</p><h2 className="mb-10 text-3xl font-bold uppercase tracking-tight md:text-5xl">From request to review.</h2><ReplayPlayer /></div></section>
    <section className="border-b border-gray-300 py-20 md:py-28"><div className="container mx-auto grid gap-12 px-4 md:grid-cols-[.7fr_1.3fr] md:px-8"><div><p className="font-mono text-xs font-bold uppercase tracking-widest text-growmax-red">A safe operating rule</p><h2 className="mt-4 text-3xl font-bold uppercase leading-tight md:text-5xl">People stay in charge.</h2></div><div className="divide-y-2 divide-gray-300 border-y-2 border-growmax-black">{[['01','Read','Minori AI works with the information and permissions available to your role.'],['02','Prepare','It shows the proposed quote, order, or product change in plain language.'],['03','Approve','A person checks the details and decides whether to continue.'],['04','Undo','Where a reversal is supported, it remains an explicit option.']].map(([n,t,d]) => <div key={n} className="grid gap-3 py-6 sm:grid-cols-[4rem_10rem_1fr] sm:items-center"><span className="font-mono text-sm text-growmax-red">{n}</span><span className="text-xl font-bold uppercase">{t}</span><span className="text-gray-600">{d}</span></div>)}</div></div></section>
    <section className="bg-growmax-black py-20 text-white md:py-28"><div className="container mx-auto px-4 md:px-8"><h2 className="max-w-3xl text-4xl font-bold uppercase leading-[.98] tracking-[-.04em] md:text-7xl">Bring today&apos;s messy work.<br />Leave with a clear next step.</h2><TrackedLink href={cta} eventName="minori_cta_clicked" eventData={{ variant: 'v1', location: 'final' }} className="mt-10 inline-flex h-14 items-center gap-3 bg-growmax-red px-7 font-mono text-xs font-bold uppercase tracking-widest text-white">Book a conversation <ArrowRight className="h-4 w-4" /></TrackedLink><div className="mt-16 grid gap-4 border-t border-white/20 pt-8 text-sm text-gray-300 sm:grid-cols-3"><div className="flex gap-3"><Check className="h-4 w-4 text-growmax-red" />Customer pricing and terms</div><div className="flex gap-3"><Check className="h-4 w-4 text-growmax-red" />Human approval before writes</div><div className="flex gap-3"><Check className="h-4 w-4 text-growmax-red" />Private beta access available</div></div></div></section>
  </main>
}